### ISSUE TITLE
systemctl restart aktualizr sleeps for 45

### ISSUE THREAD

**Issue by jeremiah** [advancedtelematic/gdp-ota-setup#8]
Hi,

If aktualizr has to sleep for 45 seconds, perhaps output a message to the console or note it in the docs. Otherwise one worries that systemctl has hung.

● aktualizr.service - Aktualizr, SOTA client written in C++
   Loaded: loaded (/lib/systemd/system/aktualizr.service; enabled; vendor preset: enabled)
   Active: activating (start-pre) since Tue 2017-03-28 18:19:20 UTC; 39s ago
  Process: 518 ExecStart=/usr/bin/aktualizr --config /etc/sota.toml (code=killed, signal=TERM)
 Main PID: 518 (code=killed, signal=TERM);         : 1026 (sleep)
   CGroup: /system.slice/aktualizr.service
           └─control
             └─1026 /bin/sleep 45

Mar 28 18:19:20 raspberrypi3 systemd[1]: aktualizr.service: Converting job aktualizr.service/restart -> aktualizr.service/start
Mar 28 18:19:20 raspberrypi3 systemd[1]: aktualizr.service: cgroup is empty
Mar 28 18:19:20 raspberrypi3 systemd[1]: aktualizr.service: About to execute: /bin/sleep 45
Mar 28 18:19:20 raspberrypi3 systemd[1]: aktualizr.service: Forked /bin/sleep as 1026
Mar 28 18:19:20 raspberrypi3 systemd[1]: aktualizr.service: Changed dead -> start-pre
Mar 28 18:19:20 raspberrypi3 systemd[1]: Starting Aktualizr, SOTA client written in C++...
Mar 28 18:19:20 raspberrypi3 systemd[1026]: aktualizr.service: Executing: /bin/sleep 45

**Comment by cajun-rat** [comment]
I'm guessing this is to work-around some service startup ordering problem, but I'll have to check with @leon-anavi

**Comment by leon-anavi** [comment]
Hi @jeremiah, @cajun-rat,

The systemd service for Aktualizr is based on the systemd service that we had for RVI SOTA Client. The ExecStartPre command that waits for 45 seconds comes from there. For more details please have a look at the git log for file meta-genivi-dev/recipes-sota/rvi-sota-client/files/sota_client.service.

I agree that there is a room for improvement. I think that @jeremiah suggestion for an output a message sounds as a good idea.

Best regards,
Leon

**Comment by cajun-rat** [comment]
Sounds reasonable.  Someone might also want to investigate if the systemd files in genivi-swm recipes (https://github.com/advancedtelematic/meta-genivi-dev/tree/gdp-integration/meta-genivi-dev/recipes-sota/genivi-swm/files) could be set up to use systemd bus activation and thus avoid this race.

**Comment by jeremiah** [comment]
Is this the file you referred to @leon-anavi? --> https://github.com/GENIVI/rvi_sota_client/blob/master/run/sota_client.service

**Comment by leon-anavi** [comment]
@jeremiah this was the last version of sota_client.service: https://github.com/GENIVI/meta-genivi-dev/blob/50bb9eaf5ef68a724b797bda9ce97633853f23ee/meta-genivi-dev/recipes-sota/rvi-sota-client/files/sota_client.service 

Upon request of GDP maintainer I have removed it when I contributed the Yocto/OE recipes for adding Aktualizr and its dependencies to meta-genivi-dev.

Best regards,
Leon

**Comment by jeremiah** [comment]
Okay. So the GDP has a different sota_client.service file? 
I note that the file I've shown only has a 5 second sleep time but if we're going to change the docs (and I'm happy to work on that patch) its likely best if we know exactly how long the sleep is.

**Comment by jeremiah** [comment]
Closing since there was a request to move to public JIRA. https://at.projects.genivi.org/jira/projects/SOTA/issues/SOTA-6?filter=allopenissues
